const {chromium}=require('playwright');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const output=fs.mkdtempSync(path.join(require('node:os').tmpdir(),'immo-browser-'));
const baseURL=process.env.BASE_URL||'http://127.0.0.1:8765';
(async()=>{
const browser=await chromium.launch({headless:true,executablePath:process.env.CHROME_PATH});const page=await browser.newPage({viewport:{width:1440,height:1100}});const errors=[];
page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text())});
const geo={features:[{type:'Feature',geometry:{type:'Point',coordinates:[5.539,43.216]},properties:{label:'1 bis Avenue de Verdun 13260 Cassis',citycode:'13022',postcode:'13260',score:.95}}]};
const rows=Array.from({length:8},(_,i)=>({id_mutation:'sale-'+i,numero_disposition:1,nature_mutation:'Vente',type_local:'Appartement',valeur_fonciere:480000+i*30000,surface_reelle_bati:85+i*2,longitude:5.539+(i-3)*.002,latitude:43.216+(i%3-1)*.002,date_mutation:new Date(Date.now()-180*86400000).toISOString().slice(0,10),id_parcelle:'p'+i,adresse_nom_voie:'Rue témoin '+(i+1),nombre_pieces_principales:4}));
await page.route('https://data.geopf.fr/**',r=>r.fulfill({json:geo}));
await page.route('https://cadastre.data.gouv.fr/**',r=>r.fulfill({json:{features:[{properties:{code:'AB',prefixe:'000'},geometry:{coordinates:[[[5.53,43.21],[5.55,43.21],[5.55,43.23],[5.53,43.21]]]}}]}}));
await page.route('https://dvf-api.data.gouv.fr/**',r=>r.fulfill({json:{data:rows}}));
await page.goto(baseURL);
await page.selectOption('#property-type','Appartement');await page.fill('#address','1 bis Avenue de Verdun 13260 Cassis');await page.fill('#surface','96');
await page.locator('#property-details summary').click();await page.fill('#property-title','Haut de villa · Cassis');await page.selectOption('#configuration','Haut de villa');await page.fill('#units','2');await page.selectOption('#condition','Différent selon les logements');await page.selectOption('#parking','Aucun');await page.fill('#veranda','23');await page.fill('#terrace','10');await page.selectOption('#garden','Commun');await page.selectOption('#pool','Commune');await page.fill('#description','Deux logements : 48 m² à rénover et 47 m² rénovés. Surfaces déclarées à confirmer.');await page.fill('#strengths','Vue dégagée, proximité du port.');await page.fill('#concerns','Absence de stationnement. <img src=x onerror=alert(1)>');
await page.setInputFiles('#property-photo', path.join(__dirname,'../dist/maison.png'));
await page.click('#submit');await page.waitForSelector('.dossier');assert.equal(await page.locator('.report-photo').count(),1);assert.equal(await page.locator('.report-sale').count(),8);assert.equal(await page.locator('.numbered-marker').count(),8);
const initial=await page.locator('.value').textContent();
await page.fill('#asking-price','750000');await page.fill('#agency-fees','4');assert.match(await page.locator('#position-summary').innerText(),/720[\s\u202f]000/);
assert.equal(await page.locator('.value').textContent(),initial);
await page.locator('[data-exclude="1"]').click();assert.equal(await page.locator('.is-excluded').count(),0);
await page.fill('#reason-1','Environnement différent');await page.locator('[data-exclude="1"]').click();assert.equal(await page.locator('.is-excluded').count(),1);assert.notEqual(await page.locator('.value').textContent(),initial);assert.match(await page.locator('#exclusion-log').innerText(),/Environnement différent/);
await page.locator('[data-locate="2"]').click();await page.getByRole('button',{name:'Voir cette vente',exact:true}).click();assert.equal(await page.evaluate(()=>document.activeElement.id),'sale-2');
await page.screenshot({path:path.join(output,'desktop.png'),fullPage:true});
await page.evaluate(()=>PropertyReport.preparePrint());
await page.pdf({path:path.join(output,'report.pdf'),format:'A4',printBackground:true});
for(let i=2;i<=8;i++){await page.fill('#reason-'+i,'Non comparable');await page.locator('[data-exclude="'+i+'"]').click();}
assert.equal((await page.locator('.value').innerText()).trim(),'—');assert.match(await page.locator('#position-summary').innerText(),/Aucune comparaison/);
await page.locator('[data-exclude="1"]').click();assert.match(await page.locator('.range').innerText(),/Moins de trois/);
await page.setViewportSize({width:390,height:844});await page.screenshot({path:path.join(output,'mobile.png'),fullPage:true});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
await page.getByRole('button',{name:'Nouvelle estimation',exact:true}).click();assert.equal(await page.locator('#result').getAttribute('data-state'),'idle');
await page.selectOption('#property-type','Garage');assert.equal(await page.locator('#property-details').isVisible(),false);
await page.fill('#address','1 bis Avenue de Verdun 13260 Cassis');
await page.route('https://dvf-api.data.gouv.fr/**',r=>r.fulfill({json:{data:[{...rows[0],type_local:'Dépendance',nombre_lots:1,lot1_numero:'1',valeur_fonciere:25000,surface_reelle_bati:null}]}}));
await page.click('#submit');await page.waitForSelector('.value');assert.match(await page.locator('h2').innerText(),/Prix des dépendances/);
console.log(JSON.stringify({initial,errors,output},null,2));await browser.close();if(errors.length)process.exitCode=1;
})().catch(e=>{console.error(e);process.exit(1)});
